In [1]:
import numpy as np
a = np.array([1,3,7,9])
print(a)

[1 3 7 9]


# Vectorization

In [ ]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c= np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version :" + str(1000*(toc-tic)) + "ms")
c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("for loop :" + str(1000*(toc-tic)) + "ms")


# Broadcasting in Python

In [3]:
import numpy as np
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])
print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Some examples for broadcasting numpy

In [8]:
a = np.random.randn(5)
print(a)

[ 0.86516415  1.52913747  0.58538056  0.59534182 -0.28992696]


In [9]:
print(a.shape)

(5,)


In [10]:
print(a.T)

[ 0.86516415  1.52913747  0.58538056  0.59534182 -0.28992696]


In [11]:
print(np.dot(a, a.T))

3.867930346966168


In [12]:
a = np.random.randn(5, 1)
print(a)

[[-1.30665378]
 [-1.86479016]
 [ 1.17163927]
 [-0.98378383]
 [-1.04551018]]


In [13]:
print(a.T)

[[-1.30665378 -1.86479016  1.17163927 -0.98378383 -1.04551018]]


In [14]:
print(np.dot(a, a.T))

[[ 1.70734411  2.43663512 -1.53092689  1.28546486  1.36611983]
 [ 2.43663512  3.47744235 -2.18486139  1.83455041  1.9496571 ]
 [-1.53092689 -2.18486139  1.37273859 -1.15263977 -1.22496079]
 [ 1.28546486  1.83455041 -1.15263977  0.96783062  1.02855601]
 [ 1.36611983  1.9496571  -1.22496079  1.02855601  1.09309154]]


In [15]:
k = np.random.randn(2, 3)
j = np.random.randn(2, 1)
m = k + j
print(k)

[[ 0.29530546 -1.45967881  0.90648168]
 [ 0.26119432 -1.05851359 -0.73099444]]


In [16]:
print(k, j)

[[ 0.29530546 -1.45967881  0.90648168]
 [ 0.26119432 -1.05851359 -0.73099444]] [[ 1.41903376]
 [-0.93504614]]


In [17]:
print(j)

[[ 1.41903376]
 [-0.93504614]]


In [18]:
print(m)

[[ 1.71433923 -0.04064505  2.32551544]
 [-0.67385182 -1.99355972 -1.66604058]]


In [20]:
print(m.shape)

(2, 3)


In [26]:
p = np.random.randn(4, 3)
l = np.random.randn(3, 2)
q  = p * l
print(p)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [27]:
print(p)

[[-0.33397588 -0.40989727 -0.62356525]
 [-1.02288359 -0.7338046   2.13398948]
 [ 0.22794931  1.38861069 -1.39479969]
 [-1.15170826 -0.76730624  0.13757393]]


In [28]:
print(l)

[[-0.71403893  0.94094441]
 [-0.129377   -0.84783929]
 [-0.63802083  1.10308225]]


In [29]:
print(q.shape)

NameError: name 'q' is not defined

In [31]:
q = p * l
print(q)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [32]:
q = np.dot(p, l)

In [33]:
print(q)

[[ 0.68935068 -0.65456948]
 [-0.5362136   2.01363769]
 [ 0.54749228 -2.50140984]
 [ 0.83386128 -0.28138571]]


In [34]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [35]:
print(c.shape)

(12288, 45)


In [37]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
  for j in range(4):
    f = a[i][j] + b[j]

In [38]:
print(f)

[ 0.41225126  2.28227551  1.0451949   0.39751085 -0.69945508  0.83352763
 -2.76919632 -0.29554291  0.21202522  0.29126077 -0.32744232 -0.9343649
  1.00582505  0.37051212 -0.73138452 -1.30560306 -0.59671141  0.05837952
  0.77420686 -0.88763531 -1.03179935  0.56470808  1.26326846 -0.0480113
  0.80248716 -2.00079325  0.18146493 -1.21805606 -1.75203914  0.1469906
 -0.60566117 -0.92418614  0.97239026 -0.27255421 -1.70793484  2.49298618
 -0.84536914  1.23841656 -0.96610175  1.08331683 -0.19226112 -0.18708762
 -0.93805936  0.46057876 -0.56536056]


In [39]:
print(i)

2


In [40]:
print(j)

3


In [44]:
a = np.random.randn(4, 3)
b = np.random.randn(3, 2)
##c = a*b

In [45]:
print(c.shape)

(3, 3)
